# Generated by Django 5.1.4 on 2024-12-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tarea_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(null=True),
        ),
    ]
