# Generated by Django 5.1.4 on 2024-12-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tarea_importante'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
